Final project:

Testing with Covid care dataset and nytimes country level cumulative cases data    
https://github.com/covidcaremap/covid19-healthsystemcapacity/tree/master/data    
https://github.com/nytimes/covid-19-data

In [23]:
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
covid_care_df = pd.read_csv (r'us_healthcare_capacity-county-CovidCareMap.csv')
us_counties_df = pd.read_csv(r'us-counties.csv')

In [38]:
covid_care_df.columns = covid_care_df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
covid_care_df = covid_care_df.rename(columns={'county_name': 'county'})
covid_care_df

,fips_code,state,county,staffed_all_beds,staffed_icu_beds,licensed_all_beds,all_bed_occupancy_rate,icu_bed_occupancy_rate,population,population_20+,population_65+,staffed_all_beds_[per_1000_people],staffed_all_beds_[per_1000_adults_20+],staffed_all_beds_[per_1000_elderly_65+],staffed_icu_beds_[per_1000_people],staffed_icu_beds_[per_1000_adults_20+],staffed_icu_beds_[per_1000_elderly_65+],licensed_all_beds_[per_1000_people],licensed_all_beds_[per_1000_adults_20+],licensed_all_beds_[per_1000_elderly_65+]
0,2016,AK,Aleutians West,0.0,0.0,0.0,NaN,NaN,5723.0,4983.0,394.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,2020,AK,Anchorage,979.0,73.0,1149.0,0.66,0.71,291538.0,213508.0,32333.0,3.358,4.585,30.279,0.250,0.342,2.258,3.941,5.382,35.536
county,2050,AK,Bethel,34.0,0.0,37.0,0.40,NaN,18216.0,11082.0,1402.0,1.866,3.068,24.251,0.000,0.000,0.000,2.031,3.339,26.391
3,2070,AK,Dillingham,18.0,0.0,18.0,0.15,NaN,5000.0,3278.0,470.0,3.600,5.491,38.298,0.000,0.000,0.000,3.600,5.491,38.298
4,2090,AK,Fairbanks North Star,145.0,13.0,175.0,0.46,0.66,98971.0,72505.0,10204.0,1.465,2.000,14.210,0.131,0.179,1.274,1.768,2.414,17.150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2532,56037,WY,Sweetwater,74.0,10.0,115.0,0.25,0.23,43051.0,30621.0,5214.0,1.719,2.417,14.193,0.232,0.327,1.918,2.671,3.756,22.056
2533,56039,WY,Teton,48.0,6.0,48.0,0.36,0.33,23081.0,18512.0,3558.0,2.080,2.593,13.491,0.260,0.324,1.686,2.080,2.593,13.491
2534,56041,WY,Uinta,105.0,6.0,225.0,0.58,0.11,20299.0,13973.0,2858.0,5.173,7.514,36.739,0.296,0.429,2.099,11.084,16.102,78.726
2535,56043,WY,Washakie,18.0,0.0,18.0,0.29,NaN,7885.0,5914.0,1710.0,2.283,3.044,10.526,0.000,0.000,0.000,2.283,3.044,10.526
2536,56045,WY,Weston,12.0,0.0,12.0,0.60,NaN,6967.0,5408.0,1429.0,1.722,2.219,8.397,0.000,0.000,0.000,1.722,2.219,8.397

In [13]:
us_counties_df

             date      county       state     fips  cases  deaths
0      2020-01-21   Snohomish  Washington  53061.0      1       0
1      2020-01-22   Snohomish  Washington  53061.0      1       0
2      2020-01-23   Snohomish  Washington  53061.0      1       0
3      2020-01-24        Cook    Illinois  17031.0      1       0
4      2020-01-24   Snohomish  Washington  53061.0      1       0
...           ...         ...         ...      ...    ...     ...
81334  2020-04-22    Sublette     Wyoming  56035.0      1       0
81335  2020-04-22  Sweetwater     Wyoming  56037.0     10       0
81336  2020-04-22       Teton     Wyoming  56039.0     63       0
81337  2020-04-22       Uinta     Wyoming  56041.0      6       0
81338  2020-04-22    Washakie     Wyoming  56043.0      4       0

[81339 rows x 6 columns]

In [47]:
len(covid_care_df.county.unique())
#len(us_counties_df.county.unique())

1568

We have 1568 counties recorded in the CovidCare dataset and 1660 counties recorded in the US cases of covid-19 dataset.

In [49]:
s1 = pd.merge(covid_care_df, us_counties_df, how='left', on=['county'])
s1

,fips_code,state_x,county,staffed_all_beds,staffed_icu_beds,licensed_all_beds,all_bed_occupancy_rate,icu_bed_occupancy_rate,population,population_20+,...,staffed_icu_beds_[per_1000_adults_20+],staffed_icu_beds_[per_1000_elderly_65+],licensed_all_beds_[per_1000_people],licensed_all_beds_[per_1000_adults_20+],licensed_all_beds_[per_1000_elderly_65+],date,state_y,fips,cases,deaths
0,2016,AK,Aleutians West,0.0,0.0,0.0,NaN,NaN,5723.0,4983.0,...,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN
1,2020,AK,Anchorage,979.0,73.0,1149.0,0.66,0.71,291538.0,213508.0,...,0.342,2.258,3.941,5.382,35.536,2020-03-12,Alaska,2020.0,1.0,0.0
2,2020,AK,Anchorage,979.0,73.0,1149.0,0.66,0.71,291538.0,213508.0,...,0.342,2.258,3.941,5.382,35.536,2020-03-13,Alaska,2020.0,1.0,0.0
3,2020,AK,Anchorage,979.0,73.0,1149.0,0.66,0.71,291538.0,213508.0,...,0.342,2.258,3.941,5.382,35.536,2020-03-14,Alaska,2020.0,1.0,0.0
4,2020,AK,Anchorage,979.0,73.0,1149.0,0.66,0.71,291538.0,213508.0,...,0.342,2.258,3.941,5.382,35.536,2020-03-15,Alaska,2020.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326214,56043,WY,Washakie,18.0,0.0,18.0,0.29,NaN,7885.0,5914.0,...,0.000,0.000,2.283,3.044,10.526,2020-04-19,Wyoming,56043.0,4.0,0.0
326215,56043,WY,Washakie,18.0,0.0,18.0,0.29,NaN,7885.0,5914.0,...,0.000,0.000,2.283,3.044,10.526,2020-04-20,Wyoming,56043.0,4.0,0.0
326216,56043,WY,Washakie,18.0,0.0,18.0,0.29,NaN,7885.0,5914.0,...,0.000,0.000,2.283,3.044,10.526,2020-04-21,Wyoming,56043.0,4.0,0.0
326217,56043,WY,Washakie,18.0,0.0,18.0,0.29,NaN,7885.0,5914.0,...,0.000,0.000,2.283,3.044,10.526,2020-04-22,Wyoming,56043.0,4.0,0.0
326218,56045,WY,Weston,12.0,0.0,12.0,0.60,NaN,6967.0,5408.0,...,0.000,0.000,1.722,2.219,8.397,NaN,NaN,NaN,NaN,NaN